汎用コマンド解釈処理部分の作成
ca45382/shioriBotDotNet pull request #125
Opened 2021-07-26 18:19 UTC by ca45382

2021-08-13 19:49 UTC, cllightz commented on DataType/ProgressStatus.cs
> +        Fin,
あんまり略さないほうがいいと思います

2021-08-13 19:57 UTC, cllightz commented on DataType/WarningType.cs
> +        LongComment,
`TooLongComment` のほうがよさそうです

2021-08-13 20:00 UTC, cllightz commented on Extension/IEnumerableExtension.cs
> +    public static class EnumerableExtension
クラス名の変更に合わせてファイル名も `EnumerableExtension.cs` にしたいですね

2021-08-13 20:05 UTC, cllightz commented on Script/Program.cs
> +                await CommandMapper.Invoke(commandEventArgs);
79行目のところでわざわざローカル変数に入れる必要は無くて、83行目の `Invoke()` の引数リスト内でnewすればいいと思います

2021-08-13 20:05 UTC, cllightz commented on Script/Program.cs
> +
ここの空行は無い方が好きです

2021-08-13 20:11 UTC, cllightz commented on Script/ClanBattle/BattleReservationSummary.cs
> +            }
if-else文の前後には空行を入れたいです。

2021-08-13 20:12 UTC, cllightz commented on Script/ClanBattle/BattleReservationSummary.cs
> +            }
caseラベルが1個だけならswitch文ではなくif文を使うべきかと思います。

今後caseラベルが増えていきそうであれば、そのときにswitch文にすればいいと思います。

2021-08-13 20:16 UTC, cllightz commented on Script/ClanBattle/BattleReservationSummary.cs
> +                    fieldBuilder.Value = "\n\u200b";
`\u200b` はzwspですが、何のために入れているのでしょうか？
zwspを入れないと空行が自動的に削除されて行が詰められてしまう、とかでしょうか？
理由が無ければ（消しても動作が変わらないのであれば） `"\n"` にすべきかと思います。

2021-08-13 20:17 UTC, cllightz commented on Script/ClanBattle/BattleReservationSummary.cs
> +
不要な空行

2021-08-13 20:18 UTC, cllightz commented on Script/ClanBattle/BattleReservationSummary.cs
> +            var messageComponent = (SocketMessageComponent)socketInteraction;
`SocketInteraction` で受け取って即 `SocketMessageComponent` にキャストするのであれば、最初から `SocketMessageComponent` で受け取るのが良いかと思います

2021-08-13 20:23 UTC, cllightz commented on Script/ClanBattle/BattleReservationSummary.cs
> +            reservationDataSet.ForEach(x => reservationDataList[x.BossNumber - 1].Add(x));
もう少し簡潔に書けそうな気がしますが悩み中です

2021-08-13 20:26 UTC, cllightz commented on Script/ClanBattle/BattleReservationSummary.cs
> +                ButtonType.Reload.ToLongLabel(), ButtonType.Reload.ToString(), ButtonStyle.Secondary, ButtonType.Reload.ToEmoji());
行の途中で改行するときは、見やすさのために前後に空行を入れたいです。

あと、引数リスト内の要素が1行1要素になるように
```cs
hoge.Hoge(
    piyo1,
    piyo2,
    piyo3,
    piyo4
);
```
としてあるほうが個人的に好きです

2021-08-13 20:27 UTC, cllightz commented on Attribute/Command.cs
> +    public class CommandAttribute : System.Attribute
クラス名が `CommandAttribute` なのでファイル名を `CommandAttribute.cs` にしましょう

2021-08-13 20:29 UTC, cllightz commented on Script/Commands.cs
> +            }
第4引数はparamsにしてあるので、 `new[] { ... }`と書かずともOKなはずです

2021-08-13 20:30 UTC, cllightz commented on Script/Commands.cs
> +            }
第4引数はparamsにしてあるので、 `new[] { ... }`と書かずともOKなはずです

2021-08-13 20:30 UTC, cllightz commented on Script/Commands.cs
> +            }
第4引数はparamsにしてあるので、 `new[] { ... }`と書かずともOKなはずです

2021-08-13 20:30 UTC, cllightz commented on Script/Commands.cs
> +            }
第4引数はparamsにしてあるので、 `new[] { ... }`と書かずともOKなはずです

2021-08-13 20:30 UTC, cllightz commented on Script/Commands.cs
> +            }
第4引数はparamsにしてあるので、 `new[] { ... }`と書かずともOKなはずです

2021-08-13 20:30 UTC, cllightz commented on Script/Commands.cs
> +            }
第4引数はparamsにしてあるので、 `new[] { ... }`と書かずともOKなはずです

2021-08-13 20:30 UTC, cllightz commented on Script/Commands.cs
> +            }
第4引数はparamsにしてあるので、 `new[] { ... }`と書かずともOKなはずです

2021-08-13 20:30 UTC, cllightz commented on Script/Commands.cs
> +            }
第4引数はparamsにしてあるので、 `new[] { ... }`と書かずともOKなはずです

2021-08-13 20:31 UTC, cllightz commented on Script/Commands.cs
> +            }
第4引数はparamsにしてあるので、 `new[] { ... }`と書かずともOKなはずです

2021-08-13 20:31 UTC, cllightz commented on Script/Commands.cs
> +             }
第4引数はparamsにしてあるので、 `new[] { ... }`と書かずともOKなはずです

2021-08-13 20:31 UTC, cllightz commented on Script/Commands.cs
> +             }
第4引数はparamsにしてあるので、 `new[] { ... }`と書かずともOKなはずです

2021-08-13 20:31 UTC, cllightz commented on Script/Commands.cs
> +             }
第4引数はparamsにしてあるので、 `new[] { ... }`と書かずともOKなはずです

2021-08-13 20:31 UTC, cllightz commented on Script/Commands.cs
> +             }
第4引数はparamsにしてあるので、 `new[] { ... }`と書かずともOKなはずです

2021-08-13 20:31 UTC, cllightz commented on Script/Commands.cs
> +             }
第4引数はparamsにしてあるので、 `new[] { ... }`と書かずともOKなはずです

2021-08-13 20:32 UTC, cllightz commented on Script/Commands.cs
> +             }
ここは省略できるか分かりません……要確認

2021-08-13 20:33 UTC, cllightz commented on Script/Commands.cs
> +             })]
ここは省略できるか分かりません……要確認

2021-08-13 20:35 UTC, cllightz commented on Script/ClanBattle/BattleReport.cs
>          }
コンストラクタの中身が1行だけになったので式形式のコンストラクタ（ `=>` ）にもできますが、お好みでどうぞ

2021-08-13 20:39 UTC, cllightz commented on Script/ClanBattle/BattleReport.cs
> +                if (!EnumMapper.TryParse<AttackType>(Regex.Match(m_CommandEventArgs.Name, @"\D{1,3}").Value, out var attackType)
`\d` の部分と `\D{1,3}` の部分を再度取り直す処理がもったいないので、最初に `Regex.Match(m_commandEventArgs.Name, @"(\d)(\D{1,3})")` を呼んで、その返り値のMatchのGroupsを活用しましょう

2021-08-13 20:40 UTC, cllightz commented on Script/ClanBattle/BattleReport.cs
> +                    || attackType == AttackType.Unknown || attackType == AttackType.CarryOver)
if文の条件式の中で改行するならば、1行1項になるようにしたいです
```cs
if (hoge
    || huga
    || piyo)
{
```

2021-08-13 20:43 UTC, cllightz commented on Script/ClanBattle/BattleReport.cs
> +            if (reportData.BossNumber < CommonDefine.MinBossNumber || reportData.BossNumber > CommonDefine.MaxBossNumber)
個人的には
```cs
reportData.BossNumber < CommonDefine.MinBossNumber || CommonDefine.MaxBossNumber < reportData.BossNumber
```
という並びの方が好きです
（数直線のように左から小→大で並んでいると見やすい気がするため）

2021-08-13 20:43 UTC, cllightz commented on Script/ClanBattle/BattleReport.cs
> +                _ = m_CommandEventArgs.SocketUserMessage.AddReactionAsync(new Emoji(ReactionType.Success.ToLabel()));
ここ `ToEmoji()` 使えませんか？

2021-08-13 20:44 UTC, cllightz commented on Script/ClanBattle/BattleReport.cs
> +            if (m_CommandEventArgs.Arguments.Count == 1
if文の前には空行を入れたいです

2021-08-13 20:48 UTC, cllightz commented on Script/ClanBattle/BattleReport.cs
> +                .OrderBy(x => x.DateTime).Last();
「 `x.DateTime` が最大となる `x` を取りたい」ということのためだけに `OrderBy()` をするのは非合理的なので、 `.MaxBy(x => x.DateTime)` と書けるような拡張メソッドを定義しちゃいましょう

2021-08-13 20:49 UTC, cllightz commented on DataType/InfomationType.cs
>          DeleteInsted,
Insteadの誤字っぽい

2021-08-13 20:49 UTC, cllightz commented on Database/Shiori/DatabaseReservationController.cs
> +            try
try-catch文の前には空行を入れたいです

2021-08-13 20:51 UTC, cllightz commented on Database/Shiori/DatabaseReservationController.cs
> +            var updateData = databaseConnector.ReservationData
行の途中で改行するときは、その前に空行を入れたいです
（この長さくらいなら途中改行せずとも1行にしちゃっていいレベルだと思います）

2021-08-13 20:55 UTC, cllightz commented on Script/ClanBattle/BattleReport.cs
> +            if (reportData.BossNumber < CommonDefine.MinBossNumber || reportData.BossNumber > CommonDefine.MaxBossNumber)
もしくは
```cs
public static bool IsInRange(this int value, int min, int max)
    => min <= value && value <= max;
```
という拡張メソッドを作ってしまうのも良いかと思います
（結構コード量を減らせるので）

2021-08-13 20:59 UTC, cllightz commented on DataModel/Shiori/ClanData.cs
>              }
このメソッドに「来月削除」と書いてありますが、消し忘れです？
（2ヶ月前に書かれたやつです）

2021-08-13 21:00 UTC, cllightz commented on DataModel/Shiori/ClanData.cs
>              }
この下の `GetNowLap()` もですね

2021-08-13 21:01 UTC, cllightz commented on DataModel/CommandEventArgs.cs
> +
ここの空行に強い意味がなければ消してもらって

2021-08-13 21:03 UTC, cllightz commented on Script/ClanBattle/BattleReport.cs
> +            if (reportData.BossNumber < CommonDefine.MinBossNumber || reportData.BossNumber > CommonDefine.MaxBossNumber)
あまりにも頻出するので
```cs
public static bool IsValidBossNumber(this int value)
    => CommonDefine.MinBossNumber <= value && value <= CommonDefine.MaxBossNumber;
```
を定義するのが最善策かもしれません

2021-08-13 21:04 UTC, cllightz commented on Script/ClanBattle/BattleReport.cs
> +                || bossNumber > CommonDefine.MaxBossNumber || bossNumber < CommonDefine.MinBossNumber
https://github.com/ca45382/shioriBotDotNet/pull/125/files#r688779804

2021-08-13 21:05 UTC, cllightz commented on Script/ClanBattle/BattleReport.cs
> +            var reportData = new ReportData()
ここの `()` は省略できます

2021-08-13 21:05 UTC, cllightz commented on Script/ClanBattle/BattleReport.cs
>              if (DatabaseReportDataController.DeleteReportData(clanReportData))
if文の前には空行を入れたいです

2021-08-13 21:07 UTC, cllightz commented on Script/ClanBattle/BattleCarryOver.cs
>                  .OrderBy(x => x.DateTime);
行の途中で改行するときは、後ろに空行を入れたいです

2021-08-13 21:07 UTC, cllightz commented on Script/ClanBattle/BattleCarryOver.cs
> +                string.Format(EnumMapper.ToLabel(InfomationType.DeleteAllCarryOverData), TimeDefine.SuccessMessageDisplayTime));
行の途中で改行するときは、前に空行を入れたいです

2021-08-13 21:08 UTC, cllightz commented on Script/ClanBattle/BattleCarryOver.cs
> +            _ = m_CommandEventArgs.SocketUserMessage.AddReactionAsync(new Emoji(ReactionType.Success.ToLabel()));
`ToEmoji()` を使えそう？

2021-08-13 21:09 UTC, cllightz commented on Script/ClanBattle/BattleCarryOver.cs
>              }
```cs
DatabaseCarryOverController.DeleteCarryOverData(carryOverList[条件演算子]);
```
の1行にできそうです

2021-08-13 21:10 UTC, cllightz commented on Script/ClanBattle/BattleCarryOver.cs
>                  .OrderBy(x => x.DateTime).ToArray();
メソッドチェーンで改行するときは、1行1メソッドになるように
```cs
    .OrderBy( ... )
    .ToArray();
```
としたいです。

2021-08-13 21:11 UTC, cllightz commented on Script/ClanBattle/BattleCarryOver.cs
> +                _ = m_CommandEventArgs.SocketUserMessage.AddReactionAsync(new Emoji(ReactionType.Success.ToLabel()));
`ToEmoji()` にできそう？

2021-08-13 21:12 UTC, cllightz commented on Script/ClanBattle/BattleCarryOver.cs
> +                || number > CommonDefine.MaxReportNumber || number <= 0)
if文の条件式の途中で改行するときは1行1項にしたいです
```cs
if (hoge
    || hoge
    || hoge)
{
```

2021-08-13 21:12 UTC, cllightz commented on Script/ClanBattle/BattleCarryOver.cs
> +                throw new ArgumentOutOfRangeException();
throwするときはMessageも書いておくと吉です

2021-08-13 21:12 UTC, cllightz commented on Script/ClanBattle/BattleCarryOver.cs
> +                throw new ArgumentNullException();
throwするときはMessageも書いておくと吉です

2021-08-13 21:13 UTC, cllightz commented on Script/ClanBattle/BattleCarryOver.cs
> +                ulong.TryParse(m_CommandEventArgs.Arguments[0], out userID))
if文の条件式の途中で改行するときは、 `||` や `&&` が行頭にあったほうが読みやすいと思います。
```cs
if (hoge
    || hoge)
{
```

2021-08-13 21:15 UTC, cllightz commented on Script/ClanBattle/BattleCarryOver.cs
> +            SocketGuildUser targetUser;
```cs
var targetUser = 条件式 ? m_CommandEventArgs.Role.Guild.GetUser(userID) : throw new ArgumentNullException("message");
```
と書けそうな気がしました

2021-08-13 21:16 UTC, cllightz commented on Script/ClanBattle/BattleCarryOver.cs
> +                _ = m_CommandEventArgs.SocketUserMessage.AddReactionAsync(new Emoji(ReactionType.Success.ToLabel()));
`ToEmoji()` にできそう？

2021-08-13 21:16 UTC, cllightz commented on Script/ClanBattle/BattleCarryOver.cs
> +            bool result = false;
varにできます

2021-08-13 21:18 UTC, cllightz commented on Script/ClanBattle/BattleCarryOver.cs
> +                || bossNumber < CommonDefine.MinBossNumber || bossNumber > CommonDefine.MaxBossNumber
https://github.com/ca45382/shioriBotDotNet/pull/125#discussion_r688776511

2021-08-13 21:18 UTC, cllightz commented on Script/ClanBattle/BattleCarryOver.cs
> +                || remainTime < CommonDefine.MinBattleTime || remainTime > CommonDefine.MaxBattleTime
https://github.com/ca45382/shioriBotDotNet/pull/125#discussion_r688776511
と同様に `IsValidBattleTime()` という拡張メソッドを作ってもいいかもしれませんね

2021-08-13 21:20 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
> +                || lap > ClanBattleDefine.MaxLapNumber || lap <= 0)
https://github.com/ca45382/shioriBotDotNet/pull/125#discussion_r688776511
と同様に `IsValidLapNumber` という拡張メソッドを定義してもいいかもしれませんね

2021-08-13 21:20 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
> +        }
式形式のメソッドにできますが、お好みでどうぞ

2021-08-13 21:20 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
> +        }
式形式のメソッドにできますが、お好みでどうぞ

2021-08-13 21:21 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
> +                userProgressData = new ProgressData()
`()` は省略できますが、お好みでどうぞ

2021-08-13 21:22 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
> +                   || damageNumber > CommonDefine.MaxDamageValue)
https://github.com/ca45382/shioriBotDotNet/pull/125#discussion_r688776511
と同様に `IsValidDamageValue()` という拡張メソッドを定義してもいいかもしれませんね
（DamageValueという名称が微妙なのでDamageかDamageAmountにしたい気もしますが、今回でなくてOKです）

2021-08-13 21:23 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
> +                if (!uint.TryParse(Regex.Match(m_CommandEventArgs.Name, @"\d+").ToString(), out damageNumber)
https://github.com/ca45382/shioriBotDotNet/pull/125#discussion_r688769077
と同様にGroupsを活用しましょう

2021-08-13 21:27 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
> +                    || damageNumber > CommonDefine.MaxDamageValue || remainTimeNumber > CommonDefine.MaxBattleTime)
https://github.com/ca45382/shioriBotDotNet/pull/125/files#r688786315
と
https://github.com/ca45382/shioriBotDotNet/pull/125#discussion_r688785901
と同様

2021-08-13 21:28 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
>              }
```cs
}
else
{
    return;
}
```
でいい説

2021-08-13 21:28 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
> +            }
```cs
}
else
{
    return;
}
```
でいい説

2021-08-13 21:30 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
> +            var progressDataFlag = false;
このローカル変数で判定をやりくりしてるのが妙にトリッキーな気がするので考えさせてください

2021-08-13 21:31 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
>                  .OrderByDescending(x => x.UpdateDateTime).FirstOrDefault();
行の途中で改行するときは、前に空行を入れたいです

2021-08-13 21:34 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
> +            DatabaseProgressController.DeleteProgressData(deleteData);
Early Returnの意味があまり無いので
```cs
if (deleteData != null)
{
    hoge();
}
```
でよいかと

もしかしたら
```cs
if (DatabaseProgressController.GetProgressData(m_CommandEventArgs.ClanData, m_BossNumberType) is { } deleteData)
```
と書けるかも？

2021-08-13 21:35 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
> +                IMessage lastIMessage;
インタフェースのインスタンスを入れる変数名には `I` をつけない方が好ましい

2021-08-13 21:41 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
>              }
```cs
if (lastMessage == null)
{
    try
    {
        var lastMessage = await progressChannel.GetMessageAsync(lastMessageID);

        if (removeLastMessage)
        {
            await lastIMessage.DeleteAsync();
        }

        return;
    }
    catch (Exception e)
    {
        Console.WriteLine(e.Message);
        return;
    }
}
```
か
```cs
if (lastMessage == null)
{
    try
    {
        var lastMessage = await progressChannel.GetMessageAsync(lastMessageID);

        if (removeLastMessage)
        {
            await lastIMessage.DeleteAsync();
        }
    }
    catch (Exception e)
    {
        Console.WriteLine(e.Message);
    }
    finally
    {
        return;
    }
}
```
とするとスッキリしそう

2021-08-13 21:41 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
>              }
else ifにしましょう

2021-08-13 21:42 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
> +            return;
このreturnは不要そうです

2021-08-13 21:43 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
>                  .ToArray();
https://github.com/ca45382/shioriBotDotNet/pull/125#discussion_r688782742 と同様

2021-08-13 21:43 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
>                  .ToArray();
空行も入れたい

2021-08-13 21:44 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
>                  )).ToArray();
なんだか異様に読みづらい……

2021-08-13 21:45 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
> +                .FirstOrDefault(x => x.BossNumber == (byte)m_BossNumberType && x.LapNumberFrom <= bossLap && (x.LapNumberTo == -1 || x.LapNumberTo >= bossLap));
前に空行を入れたいです

2021-08-13 21:46 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
> +               .FirstOrDefault();
```cs
.FirstOrDefault(x => x.Status != (byte)ProgressStatus.AttackDone || x.Status != (byte)ProgressStatus.Fin)
```
と書けません？

2021-08-13 21:47 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
> +        }
```cs
return (progressData = GetProgressData()) != null;
```
と書けますがお好みでどうぞ

あと式形式のメソッドにできますが、お好みでどうぞ

2021-08-13 21:48 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
> +        }
しんどい……これが最善策なのでしょうか？

2021-08-13 21:48 UTC, cllightz commented on Script/ClanBattle/BattleProgress.cs
> +
特に意味がなければ空行を消してもらって

2021-08-13 21:49 UTC, cllightz commented on Script/ClanBattle/BattleReservation.cs
>          }
式形式のコンストラクタにできますが、お好みでどうぞ

2021-08-13 21:50 UTC, cllightz commented on Script/ClanBattle/BattleReservation.cs
> +                CreateUserReservationDataMessage(m_CommandEventArgs.PlayerData));
途中改行するほどの長さではないかと思います

あと、式形式のメソッドにできますが、お好みでどうぞ

2021-08-13 21:51 UTC, cllightz commented on Script/ClanBattle/BattleReservation.cs
> +                        $"{m_CommandEventArgs.ClanData.ReservationEndTime.Hours}:00")
Label側（DescriptionAttribute側）に `:00` を書いて、43行目・44行目では `:00` とつけないでOKにしたいです

2021-08-13 21:52 UTC, cllightz commented on Script/ClanBattle/BattleReservation.cs
> +                ? ClanBattleDefine.MaxLapNumber : (m_CommandEventArgs.ClanData.ReservationLap + m_CommandEventArgs.ClanData.GetMinBossLap());
条件演算子の途中で改行するときは
```cs
var hoge = huga
    ? foo
    : bar;
```
とするのが個人的には好きです

2021-08-13 21:55 UTC, cllightz requested changes
あらかたコメントしたので対応お願いします～

2021-08-14 11:14 UTC, cllightz commented on Script/ClanBattle/BattleReservationSummary.cs
> +            if(buttonType == ButtonType.Reload)
`if (` のようにスペースを入れたいです

2021-08-14 11:17 UTC, cllightz commented on Script/ReceiveInteractionController.cs
> +                await new BattleReservationSummary(m_Role, m_ClanData).RunInteraction(m_Interaction as SocketMessageComponent);
以前だと `(SocketMessageComponent)socketInteraction` のようにキャストできないときは例外を吐く書き方でしたが、新しい方だと `as` なので `null` になってしまいます。

これについては深く考慮しないで大丈夫なやつです？

2021-08-14 11:19 UTC, cllightz commented on DataType/ErrorType.cs
>          OutOfReservationTime,
`:00` の対応いい感じだと思います。

それはそうと、13行目～20行目の行が詰まってギチギチなので適宜空行入れたいです。

2021-08-14 11:20 UTC, cllightz commented on Script/ClanBattle/BattleReservation.cs
> +            => m_CommandEventArgs.Channel.SendMessageAsync(CreateUserReservationDataMessage(m_CommandEventArgs.PlayerData));
以前のコードだと `async` を握りつぶすために `_ =` と書いてましたが、不要なんでしたっけ？

2021-08-15 07:44 UTC, ca45382 commented on Script/ClanBattle/BattleReservation.cs
> +            => m_CommandEventArgs.Channel.SendMessageAsync(CreateUserReservationDataMessage(m_CommandEventArgs.PlayerData));
asyncと書かなければ握りつぶせると思ってました

2021-08-15 11:18 UTC, ca45382 commented on Script/Commands.cs
> +             }
省略できませんでした。

2021-08-15 11:18 UTC, ca45382 commented on Script/Commands.cs
> +             })]
省略できませんでした。

2021-08-15 12:19 UTC, ca45382 commented on Script/ClanBattle/BattleProgress.cs
> +        }
すまん...

2021-08-15 12:59 UTC, ca45382 commented on Script/ClanBattle/BattleReservationSummary.cs
> +            reservationDataSet.ForEach(x => reservationDataList[x.BossNumber - 1].Add(x));
#132 で対応予定。

2021-08-15 13:00 UTC, ca45382 commented on Script/ClanBattle/BattleReport.cs
> +                if (!EnumMapper.TryParse<AttackType>(Regex.Match(m_CommandEventArgs.Name, @"\D{1,3}").Value, out var attackType)
#131 で対応予定

2021-08-15 13:01 UTC, ca45382 commented on Script/ClanBattle/BattleProgress.cs
> +            var progressDataFlag = false;
#133 で対応

2021-08-15 13:12 UTC, cllightz requested changes

2021-08-15 13:12 UTC, cllightz commented on Script/Commands.cs
> +        public static async Task EventInfomation(CommandEventArgs commandEventArgs)
Informationの誤字かと

2021-08-15 13:14 UTC, cllightz approved these changes

2021-08-15 13:15 UTC, merged