リアクションを受け取ったときの動作を修正
ca45382/shioriBotDotNet pull request #33
Opened 2021-05-01 10:49 UTC by ca45382

2021-05-01 10:49 UTC, ca45382 commented
なんか、いらないコミットも入れてしまった

2021-05-01 22:14 UTC, cllightz requested changes
細かいですが、いくつかコメントを入れました。よろしくおねがいします。

2021-05-01 22:14 UTC, cllightz commented on Script/Program.cs
> +            SocketUserMessage message = messageParam as SocketUserMessage;
右辺値で `as SocketUserMessage` って書いてるのでここは `var` でいいと思います。

2021-05-01 22:14 UTC, cllightz commented on Script/Program.cs
> +            return;
ここの `return;` は多分要らないと思います（文法上必要だったらごめんなさい）。

2021-05-01 22:14 UTC, cllightz commented on Script/ReceiveReactionController.cs
>                      reaction.UserId.ToString());
if文の前に空行を入れた方が読みやすいと思います。

2021-05-01 22:14 UTC, cllightz commented on Script/ReceiveReactionController.cs
> +                userClanData.ChannelIDs.DeclarationChannelID)
ここは1行で書いてあげた方が読みやすいと思います。

（改行を入れる目安としては、80文字くらいにすることが多いです）

2021-05-02 11:11 UTC, ca45382 commented
修正しました。

2021-05-03 16:32 UTC, cllightz requested changes
いくつかコメントを入れました。よろしくおねがいします。

2021-05-03 16:32 UTC, cllightz commented on Script/Program.cs
> +
この空行は不要だと思います。

2021-05-03 16:32 UTC, cllightz commented on Script/Program.cs
> +            }
if文の後ろに空行を入れた方がいいと思います。

2021-05-03 17:05 UTC, cllightz approved these changes
LGTM!

2021-05-03 17:06 UTC, merged